modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/BrassGoggledCoders/Podium/issues"
license="The MIT License (MIT)"

[[mods]]
    modId="podium"
    version="${version}"
    displayName="Podium"
    authors="SkySom"
    description='''
    '''

[[dependencies.podium]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
